/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "mpressive-20220427105557-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3ksh82hrta934.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:81d3dd2d-0ed3-4dc9-aacc-fc84b78b8701",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8qjwB2wTs",
    "aws_user_pools_web_client_id": "2v4j40a2uhvlrhte66da1m1di1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "impressive28f734f1f60046b5a87d808ec09dcec4103337-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
